<a href="https://colab.research.google.com/github/kushagrathisside/Breast-Cancer-Project/blob/main/Breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [34]:
dataframe = pd.read_csv("/content/Breast-Cancer-Dataset.csv")

In [35]:
dataframe

id  diagnosis(M=1, B=0)  ...  fractal_dimension_worst  SRNO
0      842302                    1  ...                  0.11890     1
1      842517                    1  ...                  0.08902     2
2    84300903                    1  ...                  0.08758     3
3    84348301                    1  ...                  0.17300     4
4    84358402                    1  ...                  0.07678     5
..        ...                  ...  ...                      ...   ...
551    926125                    1  ...                  0.09873   564
552    926424                    1  ...                  0.07115   565
553    926682                    1  ...                  0.06637   566
554    926954                    1  ...                  0.07820   567
555    927241                    1  ...                  0.12400   568

[556 rows x 33 columns]

In [36]:
y=dataframe.iloc[:,1].values

In [37]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,

In [38]:
y.shape

(556,)

In [39]:
x=dataframe.iloc[:,2:].values

In [40]:
x.shape

(556, 31)

In [41]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x)
x=imputer.transform(x)
print(x)
#for fitting some values in place of empty(null) values

[[1.799e+01 1.038e+01 1.228e+02 ... 4.601e-01 1.189e-01 1.000e+00]
 [2.057e+01 1.777e+01 1.329e+02 ... 2.750e-01 8.902e-02 2.000e+00]
 [1.969e+01 2.125e+01 1.300e+02 ... 3.613e-01 8.758e-02 3.000e+00]
 ...
 [2.013e+01 2.825e+01 1.312e+02 ... 2.572e-01 6.637e-02 5.660e+02]
 [1.660e+01 2.808e+01 1.083e+02 ... 2.218e-01 7.820e-02 5.670e+02]
 [2.060e+01 2.933e+01 1.401e+02 ... 4.087e-01 1.240e-01 5.680e+02]]


In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#label encoder encodes the two types of cancer into 0(maybe not cancerous) and 1(the other case)
y=le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 1 0 1 0 0
 0 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0
 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0
 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 1 0 0 1 0 0 0 0 0 1 1 0 

In [63]:
#now we have to divide data into 2 parts : one for training and one for testing
from sklearn.model_selection import train_test_split #****
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15,random_state=1)#**
#test_size = 0.2 means 20% data will be used for testing

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [111]:
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(x_train, y_train)
y_pred2 = classifier2.predict(x_test)
x_pred2 = classifier2.predict(x_train)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print("\nAccuracy for Logistic Regression: ")
print(accuracy_score(y_test,y_pred2))
print("\nAccuracy for Logistic Regression TRAIN: ")
accuracy_score(y_train,x_pred2)

[[48  0]
 [ 2 34]]

Accuracy for Logistic Regression: 
0.9761904761904762

Accuracy for Logistic Regression TRAIN: 


0.9872881355932204

In [90]:
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred3 = classifier3.predict(x_test)
x_pred3 = classifier3.predict(x_train)
cm = confusion_matrix(y_test, y_pred3)
print(cm)
print("\nAccuracy for RANDOM FOREST: ")
print(accuracy_score(y_test,y_pred3))
print("\nAccuracy for RANDOM FOREST TRAIN: ")
accuracy_score(y_train,x_pred3)


[[46  2]
 [ 3 33]]

Accuracy for RANDOM FOREST: 
0.9404761904761905

Accuracy for RANDOM FOREST TRAIN: 


0.9978813559322034

In [91]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier4.fit(x_train, y_train)
y_pred4 = classifier4.predict(x_test)
x_pred4 = classifier4.predict(x_train)
cm = confusion_matrix(y_test, y_pred4)
print(cm)
print("\nAccuracy for Decision Tree: ")
print(accuracy_score(y_test,y_pred4))
print("\nAccuracy for Decision Tree TRAIN: ")
accuracy_score(y_train,x_pred4)

[[41  7]
 [ 2 34]]

Accuracy for Decision Tree: 
0.8928571428571429

Accuracy for Decision Tree TRAIN: 


1.0

In [92]:
from sklearn.naive_bayes import GaussianNB
classifier5 = GaussianNB()
classifier5.fit(x_train, y_train)
y_pred5 = classifier5.predict(x_test)
x_pred5 = classifier5.predict(x_train)
cm = confusion_matrix(y_test, y_pred5)
print(cm)
print("\nAccuracy for Naives bayes: ")
print(accuracy_score(y_test,y_pred5))
print("\nAccuracy for Naive Bayes TRAIN: ")
accuracy_score(y_train,x_pred2)

[[44  4]
 [ 3 33]]

Accuracy for Naives bayes: 
0.9166666666666666

Accuracy for Naive Bayes TRAIN: 


0.9872881355932204

In [104]:
from sklearn.svm import SVC
classifier6 = SVC(kernel = 'rbf', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred6 = classifier6.predict(x_test)
x_pred6 = classifier2.predict(x_train)
cm = confusion_matrix(y_test, y_pred6)
print(cm)
print("\nAccuracy for SVC Kernel: ")
print(accuracy_score(y_test,y_pred6))
print("\nAccuracy for SVC Kernel TRAIN: ")
accuracy_score(y_train,x_pred6)

[[48  0]
 [ 2 34]]

Accuracy for SVC Kernel: 
0.9761904761904762

Accuracy for SVC Kernel TRAIN: 


0.9872881355932204

In [93]:
from sklearn.svm import SVC
classifier7 = SVC(kernel = 'linear', random_state = 0)
classifier7.fit(x_train, y_train)
y_pred7 = classifier7.predict(x_test)
x_pred7 = classifier7.predict(x_train)
cm = confusion_matrix(y_test, y_pred7)
print(cm)
print("\nAccuracy for SVC: ")
print(accuracy_score(y_test,y_pred7))
print("\nAccuracy for SVC TRAIN: ")
accuracy_score(y_train,x_pred7)

[[48  0]
 [ 1 35]]

Accuracy for Logistic Regression: 
0.9880952380952381

Accuracy for Logistic Regression TRAIN: 


0.989406779661017

In [103]:
from sklearn.neighbors import KNeighborsClassifier
classifier8 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier8.fit(x_train, y_train)
y_pred8 = classifier8.predict(x_test)
x_pred8 = classifier8.predict(x_train)
cm = confusion_matrix(y_test, y_pred8)
print(cm)
print("\nAccuracy for KNN: ")
print(accuracy_score(y_test,y_pred8))
print("\nAccuracy for KNN TRAIN: ")
accuracy_score(y_train,x_pred8)

[[47  1]
 [ 3 33]]

Accuracy for KNN: 
0.9523809523809523

Accuracy for KNN TRAIN: 


0.9703389830508474

In [120]:
#for 0.15
print("Accuracy for Logistic Regression:       ",accuracy_score(y_test,y_pred2))
print("Accuracy for Logistic Regression TRAIN: ",accuracy_score(y_train,x_pred2))
print("RANDOM FOREST:                          ", accuracy_score(y_test,y_pred3))
print("Accuracy for RANDOM FOREST TRAIN:       ",accuracy_score(y_train,x_pred3))

print("DECISION TREE:                          ",accuracy_score(y_test,y_pred4))
print("Accuracy for Decision Tree TRAIN:       ", accuracy_score(y_train,x_pred4))
print("NAIVE BAYES:                            ",accuracy_score(y_test,y_pred5))
print("Accuracy for Naive Bayes TRAIN:         ",accuracy_score(y_train,x_pred2))
print("KERNEL SVM:                             ",accuracy_score(y_test,y_pred6))
print("Accuracy for SVC Kernel TRAIN:          ",accuracy_score(y_train,x_pred6))
print("SVM:                                    ",accuracy_score(y_test,y_pred7))
print("Accuracy for SVC TRAIN:                 ", accuracy_score(y_train,x_pred7))
print("KNN:                                    ",accuracy_score(y_test,y_pred8))
print("Accuracy for KNN TRAIN:                 ",accuracy_score(y_train,x_pred8))

Accuracy for Logistic Regression:        0.9761904761904762
Accuracy for Logistic Regression TRAIN:  0.9872881355932204
RANDOM FOREST:                           0.9404761904761905
Accuracy for RANDOM FOREST TRAIN:        0.9978813559322034
DECISION TREE:                           0.8928571428571429
Accuracy for Decision Tree TRAIN:        1.0
NAIVE BAYES:                             0.9166666666666666
Accuracy for Naive Bayes TRAIN:          0.9872881355932204
KERNEL SVM:                              0.9761904761904762
Accuracy for SVC Kernel TRAIN:           0.9872881355932204
SVM:                                     0.9880952380952381
Accuracy for SVC TRAIN:                  0.989406779661017
KNN:                                     0.9523809523809523
Accuracy for KNN TRAIN:                  0.9703389830508474
