<a href="https://colab.research.google.com/github/kushagrathisside/Breast-Cancer-Project/blob/main/Breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd

In [57]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [58]:
dataframe = pd.read_csv("/content/data.csv")

In [59]:
dataframe

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [60]:
y=dataframe.iloc[:,1].values

In [61]:
y

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M

In [62]:
y.shape

(569,)

In [63]:
x=dataframe.iloc[:,2:].values

In [64]:
x.shape

(569, 31)

In [65]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x)
x=imputer.transform(x)
print(x)
#for fitting some values in place of empty(null) values

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [66]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#label encoder encodes the two types of cancer into 0(maybe not cancerous) and 1(the other case)
y=le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [67]:
#now we have to divide data into 2 parts : one for training and one for testing
from sklearn.model_selection import train_test_split #****
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)#**
#test_size = 0.2 means 20% data will be used for testing

In [68]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [69]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [70]:
y_pred = classifier.predict(x_test)

In [71]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("\nAccuracy for Linear Regression: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 3 39]]

Accuracy for Linear Regression: 


0.9649122807017544

In [72]:
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(x_train, y_train)
y_pred = classifier2.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Logistic Regression: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 2 40]]

Accuracy for Logistic Regression: 


0.9736842105263158

In [73]:
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred = classifier3.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Random Forest: ")
accuracy_score(y_test,y_pred)


[[71  1]
 [ 5 37]]

Accuracy for Random Forest: 


0.9473684210526315

In [74]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier4.fit(x_train, y_train)
y_pred = classifier4.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Decision Tree: ")
accuracy_score(y_test,y_pred)

[[72  0]
 [ 6 36]]

Accuracy for Decision Tree: 


0.9473684210526315

In [75]:
from sklearn.naive_bayes import GaussianNB
classifier5 = GaussianNB()
classifier5.fit(x_train, y_train)
y_predx = classifier5.predict(x_test)
cm = confusion_matrix(y_test, y_predx)
print(cm)
print("\nAccuracy for Naïve Bayes Algorithm: ")
accuracy_score(y_test,y_predx)

[[70  2]
 [ 4 38]]

Accuracy for Naïve Bayes Algorithm: 


0.9473684210526315

In [76]:
from sklearn.svm import SVC
classifier6 = SVC(kernel = 'rbf', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred = classifier6.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy Using Kernel SVM Algorithm: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 2 40]]

Accuracy Using Kernel SVM Algorithm: 


0.9736842105263158

In [77]:
from sklearn.svm import SVC
classifier7 = SVC(kernel = 'linear', random_state = 0)
classifier7.fit(x_train, y_train)
y_pred = classifier7.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy Using Support Vector Machine Algorithm: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 3 39]]

Accuracy Using Support Vector Machine Algorithm: 


0.9649122807017544

In [78]:
from sklearn.neighbors import KNeighborsClassifier
classifier8 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier8.fit(x_train, y_train)
y_pred = classifier8.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for KNN: ")
accuracy_score(y_test,y_pred)

[[72  0]
 [ 5 37]]

Accuracy for KNN: 


0.956140350877193

In [79]:
import xgboost
xgb = xgboost.XGBClassifier(earning_rate=0.009, n_estimators=350, subsample=0.8, max_depth=7)
xgb.fit(x_train,y_train)
prediction_xgb = xgb.predict(x_test)
cm = confusion_matrix(y_test, prediction_xgb)
print(cm)
print("\nAccuracy for XGB: ")
accuracy_score(y_test,prediction_xgb)

[[72  0]
 [ 4 38]]

Accuracy for XGB: 


0.9649122807017544