<a href="https://colab.research.google.com/github/kushagrathisside/Breast-Cancer-Project/blob/HyperParameterTuning/Breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
dataframe = pd.read_csv("/content/data.csv")

In [4]:
dataframe

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [5]:
y=dataframe.iloc[:,1].values

In [6]:
y

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M

In [7]:
y.shape

(569,)

In [8]:
x=dataframe.iloc[:,2:].values

In [9]:
x.shape

(569, 31)

In [10]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x)
x=imputer.transform(x)
print(x)
#for fitting some values in place of empty(null) values

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#label encoder encodes the two types of cancer into 0(maybe not cancerous) and 1(the other case)
y=le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [12]:
#now we have to divide data into 2 parts : one for training and one for testing
from sklearn.model_selection import train_test_split #****
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)#**
#test_size = 0.2 means 20% data will be used for testing

In [13]:
#test me transform lagega hamesha fit transform nhi lagega
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [15]:
y_pred = classifier.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("\nAccuracy for Linear Regression: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 3 39]]

Accuracy for Linear Regression: 


0.9649122807017544

In [17]:
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(x_train, y_train)
y_pred = classifier2.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Logistic Regression: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 2 40]]

Accuracy for Logistic Regression: 


0.9736842105263158

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred = classifier3.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Random Forest: ")
accuracy_score(y_test,y_pred)


[[71  1]
 [ 5 37]]

Accuracy for Random Forest: 


0.9473684210526315

In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier4.fit(x_train, y_train)
y_pred = classifier4.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Decision Tree: ")
accuracy_score(y_test,y_pred)

[[72  0]
 [ 6 36]]

Accuracy for Decision Tree: 


0.9473684210526315

In [20]:
from sklearn.naive_bayes import GaussianNB
classifier5 = GaussianNB()
classifier5.fit(x_train, y_train)
y_pred = classifier5.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Naïve Bayes Algorithm: ")
accuracy_score(y_test,y_pred)

[[70  2]
 [ 4 38]]

Accuracy for Naïve Bayes Algorithm: 


0.9473684210526315

In [21]:
from sklearn.svm import SVC
classifier6 = SVC(kernel = 'rbf', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred = classifier6.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy Using Kernel SVM Algorithm: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 2 40]]

Accuracy Using Kernel SVM Algorithm: 


0.9736842105263158

In [22]:
from sklearn.svm import SVC
classifier7 = SVC(kernel = 'linear', random_state = 0)
classifier7.fit(x_train, y_train)
y_pred = classifier7.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy Using Support Vector Machine Algorithm: ")
accuracy_score(y_test,y_pred)

[[71  1]
 [ 3 39]]

Accuracy Using Support Vector Machine Algorithm: 


0.9649122807017544

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier8 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier8.fit(x_train, y_train)
y_pred = classifier8.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for KNN: ")
accuracy_score(y_test,y_pred)

[[72  0]
 [ 5 37]]

Accuracy for KNN: 


0.956140350877193

In [27]:
modelxyz = SVC(kernel="rbf",C=30,gamma='auto')
modelxyz.fit(x_train,y_train)
modelxyz.score(x_test,y_test)

0.9649122807017544

In [43]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20,30,40,50,60,70,80],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)

clf.fit(x,y)
clf.cv_results_

{'mean_fit_time': array([0.02990212, 1.5451304 , 0.0216116 , 2.67975316, 0.01789918,
        4.38982725, 0.01766524, 4.13524318, 0.01783051, 5.60923376,
        0.01791935, 5.72623005, 0.01807461, 7.97815323, 0.01971617,
        7.93726101, 0.01765423, 7.63122673]),
 'mean_score_time': array([0.01029086, 0.00098829, 0.00586171, 0.00078259, 0.0051774 ,
        0.00076194, 0.0051949 , 0.0007658 , 0.00510898, 0.00078254,
        0.00536723, 0.00080252, 0.00508952, 0.00076923, 0.00572472,
        0.0007926 , 0.00502954, 0.00088406]),
 'mean_test_score': array([0.6274181 , 0.94553641, 0.6274181 , 0.95081509, 0.6274181 ,
        0.95081509, 0.6274181 , 0.952585  , 0.6274181 , 0.95784816,
        0.6274181 , 0.95256948, 0.6274181 , 0.95432386, 0.6274181 ,
        0.95432386, 0.6274181 , 0.95255395]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30, 40, 40, 50, 50, 60, 60,
                    70, 70, 80, 80],
              mask=[False, False, False, False, False, False, False, Fals

In [44]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.029902      0.001436         0.010291        0.002753       1   
1        1.545130      0.363439         0.000988        0.000111       1   
2        0.021612      0.003719         0.005862        0.001188      10   
3        2.679753      0.338731         0.000783        0.000021      10   
4        0.017899      0.000249         0.005177        0.000128      20   
5        4.389827      0.959890         0.000762        0.000023      20   
6        0.017665      0.000215         0.005195        0.000145      30   
7        4.135243      0.615423         0.000766        0.000018      30   
8        0.017831      0.000413         0.005109        0.000086      40   
9        5.609234      1.656255         0.000783        0.000016      40   
10       0.017919      0.000422         0.005367        0.000457      50   
11       5.726230      1.299215         0.000803        0.000098      50   
12       0.018075      0.000747         0.005090        0.000098      60   
13       7.978153      4.144207         0.000769        0.000029      60   
14       0.019716      0.000966         0.005725        0.000356      70   
15       7.937261      2.641749         0.000793        0.000065      70   
16       0.017654      0.000297         0.005030        0.000030      80   
17       7.631227      4.898339         0.000884        0.000200      80   

   param_kernel                         params  split0_test_score  \
0           rbf      {'C': 1, 'kernel': 'rbf'}           0.622807   
1        linear   {'C': 1, 'kernel': 'linear'}           0.947368   
2           rbf     {'C': 10, 'kernel': 'rbf'}           0.622807   
3        linear  {'C': 10, 'kernel': 'linear'}           0.938596   
4           rbf     {'C': 20, 'kernel': 'rbf'}           0.622807   
5        linear  {'C': 20, 'kernel': 'linear'}           0.938596   
6           rbf     {'C': 30, 'kernel': 'rbf'}           0.622807   
7        linear  {'C': 30, 'kernel': 'linear'}           0.929825   
8           rbf     {'C': 40, 'kernel': 'rbf'}           0.622807   
9        linear  {'C': 40, 'kernel': 'linear'}           0.938596   
10          rbf     {'C': 50, 'kernel': 'rbf'}           0.622807   
11       linear  {'C': 50, 'kernel': 'linear'}           0.929825   
12          rbf     {'C': 60, 'kernel': 'rbf'}           0.622807   
13       linear  {'C': 60, 'kernel': 'linear'}           0.929825   
14          rbf     {'C': 70, 'kernel': 'rbf'}           0.622807   
15       linear  {'C': 70, 'kernel': 'linear'}           0.929825   
16          rbf     {'C': 80, 'kernel': 'rbf'}           0.622807   
17       linear  {'C': 80, 'kernel': 'linear'}           0.929825   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.622807           0.631579           0.631579   
1            0.929825           0.973684           0.921053   
2            0.622807           0.631579           0.631579   
3            0.938596           0.973684           0.938596   
4            0.622807           0.631579           0.631579   
5            0.938596           0.973684           0.938596   
6            0.622807           0.631579           0.631579   
7            0.938596           0.973684           0.947368   
8            0.622807           0.631579           0.631579   
9            0.956140           0.973684           0.947368   
10           0.622807           0.631579           0.631579   
11           0.947368           0.973684           0.947368   
12           0.622807           0.631579           0.631579   
13           0.947368           0.973684           0.956140   
14           0.622807           0.631579           0.631579   
15           0.947368           0.973684           0.956140   
16           0.622807           0.631579           0.631579   
17           0.947368           0.973684           0.956140   

    split4_test_score  mean_test_score  std_test_

In [45]:
df[['param_C','param_kernel','mean_test_score']]
#df[['param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.627418
1        1       linear         0.945536
2       10          rbf         0.627418
3       10       linear         0.950815
4       20          rbf         0.627418
5       20       linear         0.950815
6       30          rbf         0.627418
7       30       linear         0.952585
8       40          rbf         0.627418
9       40       linear         0.957848
10      50          rbf         0.627418
11      50       linear         0.952569
12      60          rbf         0.627418
13      60       linear         0.954324
14      70          rbf         0.627418
15      70       linear         0.954324
16      80          rbf         0.627418
17      80       linear         0.952554

In [46]:
clf.best_score_

0.9578481602235678

In [47]:
###LINEAR REGRESSION HYPERPARAMETER TUNING

In [48]:
param_grid = [    
    {'penalty' : ['l1', 'l2', 'elasticnet', 'none'],
    'C' : np.logspace(-4, 4, 20),
    'solver' : ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter' : [100, 1000,2500, 5000]
    }
]

In [54]:
modellr=LogisticRegression()
clf2 = GridSearchCV(modellr, param_grid = param_grid, cv = 3, verbose=True, n_jobs=-1)
best_clf = clf2.fit(x,y)

Fitting 3 folds for each of 1600 candidates, totalling 4800 fits


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
2160 fits failed out of a total of 4800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: S

In [58]:
print(best_clf.best_estimator_)
print (f'Accuracy: {best_clf.score(x,y):.3f}')

LogisticRegression(C=0.0001, max_iter=5000, penalty='none')
Accuracy: 0.986


In [57]:
best_clf.best_estimator_

LogisticRegression(C=0.0001, max_iter=5000, penalty='none')