<a href="https://colab.research.google.com/github/kushagrathisside/Breast-Cancer-Project/blob/main/Breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [177]:
import pandas as pd

In [178]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [179]:
dataframe = pd.read_csv("/content/Breast-Cancer-Dataset.csv")

In [180]:
dataframe

id  diagnosis(M=1, B=0)  ...  fractal_dimension_worst  SRNO
0      842302                    1  ...                  0.11890     1
1      842517                    1  ...                  0.08902     2
2    84300903                    1  ...                  0.08758     3
3    84348301                    1  ...                  0.17300     4
4    84358402                    1  ...                  0.07678     5
..        ...                  ...  ...                      ...   ...
551    926125                    1  ...                  0.09873   564
552    926424                    1  ...                  0.07115   565
553    926682                    1  ...                  0.06637   566
554    926954                    1  ...                  0.07820   567
555    927241                    1  ...                  0.12400   568

[556 rows x 33 columns]

In [181]:
y=dataframe.iloc[:,1].values

In [182]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,

In [183]:
y.shape

(556,)

In [184]:
x=dataframe.iloc[:,2:].values

In [185]:
x.shape

(556, 31)

In [186]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x)
x=imputer.transform(x)
print(x)
#for fitting some values in place of empty(null) values

[[1.799e+01 1.038e+01 1.228e+02 ... 4.601e-01 1.189e-01 1.000e+00]
 [2.057e+01 1.777e+01 1.329e+02 ... 2.750e-01 8.902e-02 2.000e+00]
 [1.969e+01 2.125e+01 1.300e+02 ... 3.613e-01 8.758e-02 3.000e+00]
 ...
 [2.013e+01 2.825e+01 1.312e+02 ... 2.572e-01 6.637e-02 5.660e+02]
 [1.660e+01 2.808e+01 1.083e+02 ... 2.218e-01 7.820e-02 5.670e+02]
 [2.060e+01 2.933e+01 1.401e+02 ... 4.087e-01 1.240e-01 5.680e+02]]


In [187]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#label encoder encodes the two types of cancer into 0(maybe not cancerous) and 1(the other case)
y=le.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 1 0 1 0 0
 0 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0
 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0
 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0
 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 1 0 0 1 0 0 0 0 0 1 1 0 

In [188]:
#now we have to divide data into 2 parts : one for training and one for testing
from sklearn.model_selection import train_test_split #****
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15,random_state=1)#**
#test_size = 0.2 means 20% data will be used for testing

In [189]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [190]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [191]:
y_pred = classifier.predict(x_test)

In [192]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print("\nAccuracy for Linear Regression: ")
accuracy_score(y_test,y_pred)

[[48  0]
 [ 1 35]]

Accuracy for Linear Regression: 


0.9880952380952381

In [193]:
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(x_train, y_train)
y_pred = classifier2.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Logistic Regression: ")
accuracy_score(y_test,y_pred)

[[48  0]
 [ 2 34]]

Accuracy for Logistic Regression: 


0.9761904761904762

In [194]:
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred = classifier3.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Random Forest: ")
accuracy_score(y_test,y_pred)


[[46  2]
 [ 3 33]]

Accuracy for Random Forest: 


0.9404761904761905

In [195]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier4.fit(x_train, y_train)
y_pred = classifier4.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Decision Tree: ")
accuracy_score(y_test,y_pred)

[[41  7]
 [ 2 34]]

Accuracy for Decision Tree: 


0.8928571428571429

In [196]:
from sklearn.naive_bayes import GaussianNB
classifier5 = GaussianNB()
classifier5.fit(x_train, y_train)
y_pred = classifier5.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for Naïve Bayes Algorithm: ")
accuracy_score(y_test,y_pred)

[[44  4]
 [ 3 33]]

Accuracy for Naïve Bayes Algorithm: 


0.9166666666666666

In [197]:
from sklearn.svm import SVC
classifier6 = SVC(kernel = 'rbf', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred = classifier6.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy Using Kernel SVM Algorithm: ")
accuracy_score(y_test,y_pred)

[[48  0]
 [ 2 34]]

Accuracy Using Kernel SVM Algorithm: 


0.9761904761904762

In [198]:
from sklearn.svm import SVC
classifier7 = SVC(kernel = 'linear', random_state = 0)
classifier7.fit(x_train, y_train)
y_pred = classifier7.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy Using Support Vector Machine Algorithm: ")
accuracy_score(y_test,y_pred)

[[48  0]
 [ 1 35]]

Accuracy Using Support Vector Machine Algorithm: 


0.9880952380952381

In [199]:
from sklearn.neighbors import KNeighborsClassifier
classifier8 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier8.fit(x_train, y_train)
y_pred = classifier8.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\nAccuracy for KNN: ")
accuracy_score(y_test,y_pred)

[[47  1]
 [ 3 33]]

Accuracy for KNN: 


0.9523809523809523

In [200]:
import xgboost
xgb = xgboost.XGBClassifier(earning_rate=0.009, n_estimators=350, subsample=0.8, max_depth=7)
xgb.fit(x_train,y_train)
prediction_xgb = xgb.predict(x_test)
cm = confusion_matrix(y_test, prediction_xgb)
print(cm)
print("\nAccuracy for XGB: ")
accuracy_score(y_test,prediction_xgb)

[[46  2]
 [ 1 35]]

Accuracy for XGB: 


0.9642857142857143